### ISSUE TITLE
Please provide prebuilt releases

### ISSUE THREAD

**Issue by hupfdule** [YggdrasiI/NeoLayoutViewer#5]
To avoid that each user has to compile its own version, it would be good to provide prebuilt ones.

I didn't manage to compile it actually. Debians version of libunique is only 1.0. However, I am not really sure that this actually is the only problem I have.

**Comment by YggdrasiI** [comment]
Hello Hupfdule,

Debian also provides libunique-3.0-0 and libunique-3.0-dev, see
https://packages.debian.org/search?keywords=libunique

Does this already resolves your building issues?

Until now, I hadn't add a binary because it is not as easy as wished.
Building the program 'with -static' do not work out of the box. (I assume the GLib/GTK dependencies are the problematic one…)
On the other hand, providing a non-static binary, just shifts the library dependency problem.

Regards Yggdrasil

**Comment by hupfdule** [comment]
Hi,

it seems that version 3 of libunique is only missing from the buster (testing) repository. I installed it from stable and the build is working now.

Still, I think it is good to provide binary packages to avoid users having to compile (and install all the build dependencies). Even better would be to provide deb/rpm files, too, since then the runtime depencies are clearly defined in the packages.

Maybe I could help with building a debian package, since I have done that before.

**Comment by hupfdule** [comment]
Hi,

I prepared some pull request now to build a source package, a binary package and provide the directory structure for creating a debian package.

I was able to create a debian package with it. It's not clean at the moment. Lintian gives a lot of warnings, but it compiles and installs well. It is still a bit of a problem that the make src-package target uses an auto-generated version number. The changelog file in the debian directory already includes a fixed version number. That should be changed. Also the packaging should be adapted to get rid of the lintian warnings.

**Comment by YggdrasiI** [comment]
Thanks for your support on deb package creation. I've edited a few things in your debian_package pull request (#8) and merges the changes of the other pull requests, too.

Please provide me the missing steps how you generate the deb's after
'make src-package' and 'make dist-package'. Currently, I'm unsure about the final path structures, i.e. because the binary is placed at the top level in neo-layout-viewer-{VERSION}.tgz

> The changelog file in the debian directory already includes a fixed version number. That should be changed.
I'm not sure how the naming conventions works. Which part was manual set by you and which part by your tooling chain?!
Please edit the manual part to '1.2' and push a new commit to the PR.

**Comment by hupfdule** [comment]
Unfortunately creating a Debian package isn't that straight forward. Basically it is the following for each new release:

- get the upstream source package
- rename it and place it one directory above the "downstream" source package
- update changelog to the new release version
- build the package via "dpkg-buildpackage - uc - us" or via "debuild" or via pbuilder

I don't know what is the recommended practice if upstream is creating the Debian packages itself. I think it should be possible to automate this somehow. I will try to update the PR accordingly. 

I am not sure however if I have the time for it this year.

**Comment by YggdrasiI** [comment]
Take your time. I also tried a few things and can build the package with pbuilder in a Ubuntu Xenial environment. Unfortunately, I can  not build it with Debian sid/unstable as base.

**Comment by hupfdule** [comment]
I have now updated the PR with changes to build Debian packages in a cleaner way.

- The Makefile now provides a target "deb-packages" to build Debian packages
  - This uses pdebuild to build inside a chroot
  - A temporary folder tmp/ is used to not clutter the project dir or its parent dir
  - The distribution and architectures to build for are Makefile variables. The default is Debian stretch (stable) for amd64 and i386
- The Makefile now provides a target "deb-package" to build a single Debian package for the current distribution and architecture
- The Makefile now provides a target "dist" to build all distribution packages.

There are a few issues:

- While it should be possible to build for different architectures, I only managed to build for amd64 and i386. Trying to build for e.g. armhf always failed on my machine. I don't know the reason.
- Also trying to build for Ubuntu trusty or xenial fails on my machine.
- However, it may be enough to provide a package for one distribution (Debian stable) that should be installable on other Debian distributions as well as on Ubuntu distributions. Can you check whether you can install the generated Debian package on Ubuntu trusty or xenial?
- I could be possible to build for different distributions, but that requires a bit more work, since the resulting packages for e.g. Debian Stretch and Ubuntu Xenial will have the same same. These need to be renamed then before being put into the dist/ folder. Also, as I said I wasn't able to build the Ubuntu packages.
- The Debian release version should not be managed in the Makefile, but only in the debian/changelog file. Therefore either VERSION or RELEASE_VERSION should be dropped from the Makefile. This change needs to be reflected in the release script (see below).
- libunique is not contained in Debian buster and sid and also removed from Ubuntu since Bionic. It is highly deprected by Gnome/GTK and should be replaced. See https://wiki.gnome.org/Attic/LibUnique and https://developer.gnome.org/gtk3/stable/gtk-migrating-unique-GtkApplication.html.
- There are some warnings when building the debian packages:
```
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libatk-1.0.so.0 (it  uses none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libpangocairo-1.0.so.0
  (it uses none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libcairo.so.2 (it    uses
  none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libcairo-gobject.so. 2 (it uses none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libpango-1.0.so.0    (it uses none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libm.so.6 (it uses   none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libpthread.so.0 (it  uses none of the library's symbols)
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/neo-layout-viewer/usr/bin/neo_layout_viewer was not linked against libdbusmenu-glib.so. 4 (it uses none of the library's symbols)
```
  You should check whether there really are libraries linked that are actually unused and maybe reduce these dependencies.


- I also added a `release` script for easier created of releases and related artifacts.
  - It provides and easy way to check the preconditions for a release, tag it in git, build all distribution artifacts and upload those to github
  - It allows to perform a rollback in case something went wrong
  - It needs the following tools installed:
    - devscripts
    - sed
    - hub (Contained in Debian testing and unstable and Ubuntu disco, can be obtained from https://packages.debian.org/buster/amd64/hub/download)
  - It is not thoroughly tested, but I was able to create and rollback some releases with it

**Comment by YggdrasiI** [comment]
Hello Hupfdule,

sorry for my late reply, but your detailed post costs me a few days to deal with. :) At the end, I've merged your improvements and remove the libuniuqe-3.0 dependency as suggested.

>* The Makefile now provides a target "dist" to build all distribution packages.
I've removed the output directory of this target (./dist) from 'make clean'.

> There are a few issues:
> 
>* While it should be possible to build for different architectures, I only managed to build for amd64 and i386. Trying to build for e.g. armhf 
always failed on my machine. I don't know the reason.
>* Also trying to build for Ubuntu trusty or xenial fails on my machine.
>
>* However, it may be enough to provide a package for one distribution (Debian stable) that should be installable on other Debian distributions as well as on Ubuntu distributions. Can you check whether you can install the generated Debian package on Ubuntu trusty or xenial?
> 

Building for armhf also failed on my machine, but I has not investigate it yet.
The building against Ubuntu probably failed because valac isn't in *main*, but *universe*. With pbuilder [...] --components="main universe" it builds on xenial and bionic.

Is *strech* the correct Debian distribution if you or I want upload the package to the Debian repositories? I've read that we need to build against *unstable*?!



>* I could be possible to build for different distributions, but that requires a bit more work, since the resulting packages for e.g. Debian Stretch and Ubuntu Xenial will have the same same. These need to be renamed then before being put into the dist/ folder. Also, as I said I wasn't able to build the Ubuntu packages.

I've extended the version naming  scheme by 'ubuntu1' 
**UBUNTU=1 make dist** creates  *neo-layout-viewer_1.3-1ubuntu1_amd64.deb, etc.


>* The Debian release version should not be managed in the Makefile, but only in the debian/changelog file. Therefore either VERSION or RELEASE_VERSION should be dropped from the Makefile. This change needs to be reflected in the release script (see below).

The RELEASE_VERSION string will now extracted from debian/changelog.


>* libunique is not contained in Debian buster and sid and also removed from Ubuntu since Bionic. […]

Ok, I've followed your suggestion and replaced libunique.


>* There are some warnings when building the debian packages:
> 
> ```
>     dpkg-shlibdeps: warning: package could avoid a useless dependency […]
> ```
> 
> You should check whether there really are libraries linked that are actually unused and maybe reduce these dependencies.

Here, I decided to ignore the warnings. I wouldn't edit the automatic generated linking suggestions of *pkg-config --cflags --libs gtk+-3.0"*.


>* I also added a `release` script for easier created of releases and related artifacts.
>[...]
>* It is not thoroughly tested, but I was able to create and rollback some releases with it

Nice script, I slightly modified it and used it to push a first public release of the deb files (version 1.3).

How did you want continue? Are you already satisfied with a Github hosted list of deb-files or was your main target an package, directly integrated into the Debian repository? 

Regards YggdrasiI

P.S. I've added your name to the list of contributors :)

**Comment by hupfdule** [comment]
Hello,

no problem. It's obvious that it takes a bit of time to grasp all of it.
Especially since I was a little bit terse with my description of the purpose 
and the internal workings of the release script.

My original intention with this issue was only that prebuild binaries 
were supplied. Even the debian package was more of a nice-to-have,
though a very convenient one for users of Debian-based distributions.

If you want to get your package into the official Debian repo,
there is more to do (see below).

However, I still would change a few things (I think some inconsistencies
that are caused by a lack of description of my changes. Sorry for that.):

1. You are now taking the release version number from the Debian changelog.
   However, the version number in the Debian changelog includes the Debian suffix,
   that should not be included in the "upstream" version.
   Usually you would give your software a version number of e.g.
   1.3 and that would result in a Debian version number 1.3-1.
   If it is necessary to update the Debian package without any
   upstream changes, the new version number would be 1.3-2.
   I think your naming scheme when building especially for Ubuntu is correct.
   However you should check if it is necessary or if a single Debian
   package can be installed in Ubuntu as well (I actually expect that). 
   In that case you don't need to build extra Ubuntu packages.
   Please see below for my description of the release script.
2. You are taking the `dist` directory out of the `clean` target. 
   Is this necessary? I would think that it is correct to clean that up
   since it is the result of the compilation step and can easily be
   recreated.

For the current state (that the debian packages are created and publlished
by yourself) I think it is correct to build it mainly for the current stable
distribution, which is _stretch_. That should normally be installable 
on newer distributions, too, and is therefore the most convenient way for
your users to install the NeoLayoutViewer.

But you are right, if you want to get it included in the official Debian repo,
it will always be built against the current _unstable_.

## Release script

I'll try to explain my intention of the release script a bit more, what I forgot
the last time.

The script was provided to ease the creation of a _release_. It is not intended for 
development states of the application. For example, if NeoLayoutViewer exists in release 1.2,
the release script can be used to create a new release 1.3. For the development between 1.2 and 1.3
the release script is not usable.

When creating a release it asks for the new version number and suggests a default based on the current
version number (version number of the application, not the Debian version number). It also suggests the
version number for the next development iteration. This idea is taken from the way [Apache Maven](https://maven.apache.org/) 
is handling version numbers. That means real releases have version numbers like x.y or x.y.z and development versions get 
the string `-SNAPSHOT` appended to it. Those are not real release versions, but only indicate that this version is in development
and two builds with the same snapshot version number (e.g. 1.4-SNAPSHOT) are not necessarily identical.

You can decide whether you want to take that convention or use another one. The release script currently suggests such 
`-SNAPSHOT` suffixes for SNAPSHOT versions. 

Be aware that all of that only refers to the "upstream" version numbers, not the version number of the Debian package.

When building a release the script not only builds the application, but also prepares the Debian package. Therefore it calls 
`dch` to request information about the changes to that release. You can, however, call `dch -i` while developing for the next 
release to subsequently add entries to the changelog that will then already be contained in the changelog when building the next
release.

If the preparation or the performing of the release fails, the gathered information is still available in the `release_info` file.
This information can be used the restart the release process after fixing the problems or to rollback to the state before.

After building a release you should have the following artifacts:

 - neo-layout-viewer-1.3.tar.gz (The distribution-agnostic binary distribution package)
 - neo-layout-viewer-1.3-src.tar.gz (The source package for that release)
 - neo-layout-viewer-1.3-1_[arch].deb (The debian package(s) for the built architectures)
 
The script then allows to upload those artifacts to github and publish the release there.

## Getting into the official Debian repository

If you want to include NeoLayoutViewer in the official Debian repository, you don't provide prebuild Debian packages.
You actually need some mentor or sponsor in the Debian community to help you.
You should read the [Debian Developers Reference](https://www.debian.org/doc/manuals/developers-reference/index.en.html)
on information on how to get a Debian Maintainer for your package or how to find one if you do not intend to do it yourself 
(I don't have the time for doing some, therefore I am out :-)).

Maybe you should read or at least skim over the [other Debian Developer Manuals](https://www.debian.org/doc/devel-manuals).

Be aware that at least the [Debian New Maintainers Guide](https://www.debian.org/doc/maint-guide/) is mostly outdated and 
incomplete. Since you already have a basic infrastructure for building a Debian package you are already well set. However
linitian still emits some warnings, therefore some cleanup will still be necessary. But some Debian Mentors can help you 
there.

Best regards,
Hupfdule
